# Generated by Django 4.2.6 on 2023-10-30 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CritiqueAvecTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critic_title', models.CharField(default='', max_length=100)),
                ('book_ranking', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('critic_comment', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CritiqueSansTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='', max_length=100)),
                ('book_description', models.CharField(default='', max_length=100)),
                ('book_image', models.ImageField(upload_to='')),
                ('critic_title', models.CharField(default='', max_length=100)),
                ('book_ranking', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('critic_comment', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='', max_length=100)),
                ('book_description', models.CharField(default='', max_length=100)),
                ('book_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
