# Generated by Django 4.2.6 on 2023-11-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='', max_length=100)),
                ('book_description', models.CharField(default='', max_length=100)),
                ('book_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ModifyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='', max_length=100)),
                ('book_description', models.CharField(default='', max_length=100)),
                ('book_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
